definitions:
    clear_user_email_origin_on_deactivation:
        label: Clear imap email origin on deactivation
        enabled: true
        order: 150
        entity: Oro\Bundle\ImapBundle\Entity\UserEmailOrigin
        actions_configuration:
            - @find_entity:
                parameters:
                    class: JMS\JobQueueBundle\Entity\Job
                    attribute: $.pendingJob
                    where:
                        command: 'oro:imap:clear-mailbox'
                        state: 'pending'
            - @find_entity:
                parameters:
                    class: JMS\JobQueueBundle\Entity\Job
                    attribute: $.runningJob
                    where:
                        command: 'oro:imap:clear-mailbox'
                        state: 'running'
            - @tree:
                conditions:
                    @and:
                        - @empty: $.pendingJob
                        - @empty: $.runningJob
                actions:
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:imap:clear-mailbox'
    clear_imap_email_folder_on_sync_enabled_change:
        label: Clear email folder on sync enabled change
        enabled: true
        order: 150
        entity: Oro\Bundle\EmailBundle\Entity\EmailFolder
        actions_configuration:
            - @find_entity:
                parameters:
                    class: JMS\JobQueueBundle\Entity\Job
                    attribute: $.pendingJob
                    where:
                        command: 'oro:imap:clear-mailbox'
                        state: JMS\JobQueueBundle\Entity::STATE_PENDING
            - @find_entity:
                parameters:
                    class: JMS\JobQueueBundle\Entity\Job
                    attribute: $.runningJob
                    where:
                        command: 'oro:imap:clear-mailbox'
                        state: JMS\JobQueueBundle\Entity::STATE_RUNNING
            - @tree:
                conditions:
                    @and:
                        - @equal: [$syncEnabled, false]
                        - @empty: [$.pendingJob]
                        - @empty: [$.runningJob]
                actions:
                    - @create_entity:
                        class: JMS\JobQueueBundle\Entity\Job
                        attribute: $.syncJob
                        flush: true
                        arguments:
                            - 'oro:imap:clear-mailbox'

triggers:
    clear_user_email_origin_on_deactivation:
        -
            event: update
            field: isActive
    clear_imap_email_folder_on_sync_enabled_change:
        -
            event: update
            field: syncEnabled
