Oro\Bundle\ImapBundle\Entity\UserEmailOrigin:
    properties:
        imapHost:
            - NotBlank:     { groups: [Check] }
            - Length:
                min:        3
                max:        255
        imapPort:
            - NotBlank:     { groups: [Check] }
            - Type:
                type: integer
        smtpHost:
            - NotBlank: ~
            - Length:
                min:        3
                max:        255
        smtpPort:
            - NotBlank: ~
            - Type:
                type: integer
        ssl:
            - Choice:
                choices:  [ssl, tls]
        user:
            - NotBlank:     { groups: [Check] }
            - Type:
                type: string
