Oro\Bundle\ImapBundle\Entity\ImapEmailOrigin:
    properties:
        mailboxName:
            - NotBlank:     ~
        host:
            - NotBlank:     { groups: [Check] }
            - Length:
                min:        3
                max:        255
        port:
            - NotBlank:     { groups: [Check] }
            - Type:
                type: integer
        ssl:
            - Choice:
                choices:  [ssl, tls]
        user:
            - NotBlank:     { groups: [Check] }
            - Type:
                type: string
